/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsIdRouteImport } from './routes/posts/$id'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthAdmin_topicsRouteImport } from './routes/_auth/admin_topics'
import { Route as AuthAdmin_postsRouteImport } from './routes/_auth/admin_posts'
import { Route as ApiTopicsIndexRouteImport } from './routes/api/topics/index'
import { Route as ApiPostsIndexRouteImport } from './routes/api/posts/index'
import { Route as ApiTopicsIdRouteImport } from './routes/api/topics/$id'
import { Route as ApiPostsIdRouteImport } from './routes/api/posts/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdmin_topicsRoute = AuthAdmin_topicsRouteImport.update({
  id: '/admin_topics',
  path: '/admin_topics',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdmin_postsRoute = AuthAdmin_postsRouteImport.update({
  id: '/admin_posts',
  path: '/admin_posts',
  getParentRoute: () => AuthRoute,
} as any)
const ApiTopicsIndexRoute = ApiTopicsIndexRouteImport.update({
  id: '/api/topics/',
  path: '/api/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsIndexRoute = ApiPostsIndexRouteImport.update({
  id: '/api/posts/',
  path: '/api/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTopicsIdRoute = ApiTopicsIdRouteImport.update({
  id: '/api/topics/$id',
  path: '/api/topics/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsIdRoute = ApiPostsIdRouteImport.update({
  id: '/api/posts/$id',
  path: '/api/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/admin_posts': typeof AuthAdmin_postsRoute
  '/admin_topics': typeof AuthAdmin_topicsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/api/upload': typeof ApiUploadRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/': typeof PostsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
  '/api/topics/$id': typeof ApiTopicsIdRoute
  '/api/posts/': typeof ApiPostsIndexRoute
  '/api/topics/': typeof ApiTopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/admin_posts': typeof AuthAdmin_postsRoute
  '/admin_topics': typeof AuthAdmin_topicsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/api/upload': typeof ApiUploadRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts': typeof PostsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
  '/api/topics/$id': typeof ApiTopicsIdRoute
  '/api/posts': typeof ApiPostsIndexRoute
  '/api/topics': typeof ApiTopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/_auth/admin_posts': typeof AuthAdmin_postsRoute
  '/_auth/admin_topics': typeof AuthAdmin_topicsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/api/upload': typeof ApiUploadRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/': typeof PostsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
  '/api/topics/$id': typeof ApiTopicsIdRoute
  '/api/posts/': typeof ApiPostsIndexRoute
  '/api/topics/': typeof ApiTopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/login'
    | '/projects'
    | '/admin_posts'
    | '/admin_topics'
    | '/dashboard'
    | '/api/upload'
    | '/posts/$id'
    | '/posts/'
    | '/api/auth/$'
    | '/api/posts/$id'
    | '/api/topics/$id'
    | '/api/posts/'
    | '/api/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/projects'
    | '/admin_posts'
    | '/admin_topics'
    | '/dashboard'
    | '/api/upload'
    | '/posts/$id'
    | '/posts'
    | '/api/auth/$'
    | '/api/posts/$id'
    | '/api/topics/$id'
    | '/api/posts'
    | '/api/topics'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/contact'
    | '/login'
    | '/projects'
    | '/_auth/admin_posts'
    | '/_auth/admin_topics'
    | '/_auth/dashboard'
    | '/api/upload'
    | '/posts/$id'
    | '/posts/'
    | '/api/auth/$'
    | '/api/posts/$id'
    | '/api/topics/$id'
    | '/api/posts/'
    | '/api/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  PostsIdRoute: typeof PostsIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPostsIdRoute: typeof ApiPostsIdRoute
  ApiTopicsIdRoute: typeof ApiTopicsIdRoute
  ApiPostsIndexRoute: typeof ApiPostsIndexRoute
  ApiTopicsIndexRoute: typeof ApiTopicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin_topics': {
      id: '/_auth/admin_topics'
      path: '/admin_topics'
      fullPath: '/admin_topics'
      preLoaderRoute: typeof AuthAdmin_topicsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin_posts': {
      id: '/_auth/admin_posts'
      path: '/admin_posts'
      fullPath: '/admin_posts'
      preLoaderRoute: typeof AuthAdmin_postsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/topics/': {
      id: '/api/topics/'
      path: '/api/topics'
      fullPath: '/api/topics/'
      preLoaderRoute: typeof ApiTopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/': {
      id: '/api/posts/'
      path: '/api/posts'
      fullPath: '/api/posts/'
      preLoaderRoute: typeof ApiPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/topics/$id': {
      id: '/api/topics/$id'
      path: '/api/topics/$id'
      fullPath: '/api/topics/$id'
      preLoaderRoute: typeof ApiTopicsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/$id': {
      id: '/api/posts/$id'
      path: '/api/posts/$id'
      fullPath: '/api/posts/$id'
      preLoaderRoute: typeof ApiPostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthAdmin_postsRoute: typeof AuthAdmin_postsRoute
  AuthAdmin_topicsRoute: typeof AuthAdmin_topicsRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdmin_postsRoute: AuthAdmin_postsRoute,
  AuthAdmin_topicsRoute: AuthAdmin_topicsRoute,
  AuthDashboardRoute: AuthDashboardRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  ApiUploadRoute: ApiUploadRoute,
  PostsIdRoute: PostsIdRoute,
  PostsIndexRoute: PostsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPostsIdRoute: ApiPostsIdRoute,
  ApiTopicsIdRoute: ApiTopicsIdRoute,
  ApiPostsIndexRoute: ApiPostsIndexRoute,
  ApiTopicsIndexRoute: ApiTopicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
